version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64 #not needed if on windows
    image: "mysql:5.7"
    restart: always
    ports: 
      - 3307:3306
    environment :
      MYSQL_DATABASE: loanmangement
      MYSQL_USER: lmsAdmin
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
      
      
     